version: '3.8'
services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: ./mysite
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASS=password
      - DB_SERVICE=db
      - DB_PORT=5432
      - BUCKET_NAME=2222
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data: