# Generated by Django 5.0.6 on 2024-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleapi', '0002_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
