# Generated by Django 5.0.6 on 2024-06-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleapi', '0003_alter_rental_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
